fileicons/material-icons.json

Why nobody else uses .xslt extension? Is it really only me? May be it is me, who is wrong here? 😨

Map .xslt extension to XML icon

---

src/material-icons.json

This PR adds icon support for ClojureScript with `*.cljs` file extension

Use Clojure icon for ClojureScript

---

icons/terraform.svg
src/material-icons.json

I've got the icon from (the repo has MIT license):
https://github.com/jesseweed/seti-ui/blob/master/icons/terraform.svg
Changed the color to `Deep Purple 600`.

Add Terraform icon

---

src/material-icons.json

`gulpfile.babel.js` is a popular naming convention for gulp configuration that needs to be compiled using babel (e.g. written in ES6).
I've added it as a valid filename for files that fall under the gulp category.

Add gulpfile.babel.js as a valid gulp file

---

src/material-icons.json

The `.env.example` file is generally used as a template for `.env` files. It is tracked by source control, but not used as the actual configuration.
This PR gives it the same icon as `.env`.

Add support for .env.example

---

src/material-icons.json

These are commonly used extensions for Oracle PL/SQL files and should also show the database icon.

adds .pks and .pkb file detection

---

src/i18n/lang-zh-cn.ts

Hi! Thanks for so many cool material icons.
Added support for `locale: zh-CN` which is simplified Chinese language to prevent the error `Cannot find module './lang-zh-cn'` when developing other VS Code extensions.

added I18N Simplified Chinese

---

src/helpers/change-detection.ts

Check if the global value is not undefined. Otherwise it will prompt to restart every time because undefined !== true (true by default)

fixed bug in change detection

---

src/material-icons.json

"javascriptreact" is a language mode that replace the default "javascript" mode when a .js is opened in vscode. This can be done via the settings: 
````json
{
"files.associations": {
"*.js": "javascriptreact"
}
}
````
So I choose the already present "react.svg" file inside the icons folder to do the maching.

Add Language Mode "javascriptreact"

---

src/icons/fileIcons.ts

`.mjs` already has the icon from the language identifier, but this also adds the icon for [module](https://nodejs.org/api/esm.html) source maps.

add javascript icon to module files

---

src/icons/folderIcons.ts

`lang/` now uses the i18n folder icon.

add i18n icon to lang folders

---

src/icons/fileIcons.ts

Babel's upcoming v7 will add support for [`.babelrc.js` config file](https://babeljs.io/blog/2017/09/12/planning-for-7.0#babelrcjs). I updated the file association for babel to include this file. Is this the right place to add it?

Added .babelrc.js to babel associations

---

src/icons/fileIcons.ts

Added recognition for `docker-compose.override.yml` as a standard Docker file, with the standard Docker icon.

Added docker icon to the docker-compose.override.yml file

---

src/icons/fileIcons.ts

Currently `docker-compose.yaml` file icon is default `.yaml` icon, but `docker-compose.yml` is the Docker icon.
This adds `docker-compose.yaml` to the list of files using the docker icon.

Adds docker-compose.yaml file association

---

src/icons/fileIcons.ts

Fish shell scripts with the `.fish` extension currently do not have an icon assigned to them. This fixes that, treating Fish shell scripts like other shell scripts.

Assign the `console` icon to .fish files

---

src/icons/fileIcons.ts

Babel@7 also introduce `babel.config.js` as a valid babel configuration file. (reference here: https://babeljs.io/docs/en/next/babelconfigjs.html)

Add babel.config.js to the babel association list

---

icons/bitbucket.svg
src/icons/fileIcons.ts

Pretty straightforward. Added an icon for bitbucket pipelines config file.
https://bitbucket.org/product/features/pipelines
The icon came from font awesome's free brand icons collection. The color is blue 800 from the material design color swatches.
https://material.io/design/color/the-color-system.html#tools-for-picking-colors

add bitbucket icon for bitbucket pipeline yaml files

---

src/icons/fileIcons.ts

While graphql is the 'official' extension (used internally by Facebook) major tools recognise both graphql and gql.

Recognise gql extension as a GraphQL file

---

src/icons/fileIcons.ts

Sometimes `docker-compose-prod.yml` file is used. Currently Material Icon Theme does not support this file association.
See: https://docs.docker.com/compose/extends/#example-use-case

Added docker-compose-prod file icon

---

src/icons/fileIcons.ts

[Stencil](https://github.com/ionic-team/stencil/) recently [added support](https://github.com/ionic-team/stencil/blob/master/CHANGELOG.md#-0110-2018-07-31) for typed `stencil.config.ts` files in v0.11.0.
This PR simply expands support for the existing Stencil icon to include the new Typescript config file.

Add support for `stencil.config.ts` for Stencil icon

---

src/icons/fileIcons.ts

Extended the `credits` icon for use with `AUTHORS`, `AUTHORS.md`, and `AUTHORS.txt` files. The usage is pretty much the same between the authors and credits - figured the icon could be same.

Add support for `AUTHORS`

---

src/icons/fileIcons.ts

Add some other docker-compose suffixes.
To be vscode api prevent usage of glob 😕

Adding some docker compose aliases

---

src/icons/fileIcons.ts

A set of configuration files specific to Visual Studio:
- `*.vcxproj` The default Visual C++ project file.
- `*.vcxitems` A non-compiled "Shared items" project.
- `*.*.filters` Per project file grouping and filtering configuration in Visual Studio.
- `*.ruleset` Custom configuration for error/warning handling.
And adding the `.clang-tidy` configuration file with the existing mention of `.clang-format` under settings.

Adding Visual Studio C++ configuration files & .clang-tidy

---

scripts/preview/screenshots.ts

Puppeteer was not creating file icons previews without `file:` prefix inside before HTML path inside `page.goto` method.

Added file prefix to puppeteer page link

---

src/icons/fileIcons.ts

The title is self explanatory. According to the [documentation](https://www.appveyor.com/docs/build-configuration/#yaml-file-alternative-naming), this name is supported out of the box.
Some people might prefer to keep all of the CI configuration under the same format (`.gitlab-ci.yml`, `.travis.yml` and `.appveyor.yml`).
A little preview:

Added dot-file-style for AppVeyor

---

src/icons/folderIcons.ts

This is a simple proposal which makes folders named "web" have the "public" icon, as they likely have web-facing files like pages, scripts, and style-sheets, much like the "public" and "wwwroot" folders.

Add web folder icon

---

README.md
package.json
package.nls.json
src/commands/grayscale.ts
src/commands/index.ts
src/commands/restoreConfig.ts
src/commands/saturation.ts
src/i18n/lang-en.ts
src/icons/generator/iconGrayscale.ts
src/icons/generator/iconSaturation.ts
src/icons/generator/index.ts
src/icons/generator/jsonGenerator.ts
src/models/i18n/translation.ts
src/models/icons/iconJsonOptions.ts

Hi, I'm not a big fan of colored icons as I think they draw too much attention, however, I do like having different symbols for each file type.
Inspired by the awesome hack used to change the icons opacity I added a new command and configuration to allow switching all icons to grayscale. This is done by adding an SVG filter to each icon file changing its saturation to 0.
Here is an example of how it looks: (I loved it!)

Add config for grayscale icons

---

CONTRIBUTING.md
src/icons/fileIcons.ts

`.cljc` files are used with [reader conditionals](https://clojure.org/guides/reader_conditionals).
**Bonus:** removed unnecessary dot from contributing instructions

Use clojure icon for .cljc files

---

src/icons/fileIcons.ts

This adds support for the [`.cson`](https://github.com/bevry/cson) and the [`.iced` CoffeeScript](http://maxtaco.github.io/coffee-script/) file extensions, which are now both supported by **VS Code** as of https://github.com/Microsoft/vscode/pull/70686.

feat: Add `.cson` and `.iced` CoffeeScript extensions

---

src/icons/fileIcons.ts

Brotli is Google's next-generation compression standard, supported by most major web browsers. I've added `.br` files to the pre-existing default 'zip' icon. We could also use the actual Brotli icon seen on https://brotli.org/:

Add icons for Brotli

---

src/icons/fileIcons.ts

Sets the Gitlab icon for any file that ends with `.gitlab-ci.yml`.
Resolves #464

use fileExtensions for gitlab icon

---

src/icons/fileIcons.ts

Use tex icon for .dtx (DocTeX) and .ltx (LaTeX) files.

Use tex icon for .dtx and .ltx files

---

src/icons/folderIcons.ts

Since a little while in Expo React Native projects, the expo-cli has an optimize image feature which create a ".expo-shared" folder to keep track of already optimized assets. Details here: https://blog.expo.io/image-compression-with-expo-cli-d32d15cc8b73
In this pull request, I propose to associate the Expo folder icon to this .expo-shared folder.
Note: I just realized that an additional change slipped in this commit, VSCode removed a stray space before a comma when saving, which I guess is not a bad thing.

Associate ".expo-shared" with the expo folder icon

---

icons/nest-blue.svg
icons/nest-darkgreen.svg
icons/nest-green.svg
icons/nest-purple.svg
icons/nest-red.svg
icons/nest-yellow.svg
package.json
package.nls.de.json
package.nls.es.json
package.nls.fr.json
package.nls.json
package.nls.nl.json
package.nls.pl.json
package.nls.pt-BR.json
package.nls.pt-PT.json
package.nls.ru.json
package.nls.zh-CN.json
src/icons/fileIcons.ts
src/models/icons/iconPack.ts

Made essential changes to accommodate [NestJS](https://nestjs.com/) as right now icons of angular type are shown as default as both use same file naming convention, so it was essential to create a new IconType.
Main Changes made:
1. Updates the main NestJS logo color for main files (nest-cli.json, nestconfig.json ...)
2. Persistence Layer file types - blue color (dto, interfaces, entity, model, enum and repository)
3. Module file type - red color
4. Controller file type - green color
5. Service file type - yellow color
6. Decorator file type - purple color
7. Pipe file type - dark green color
8. IconType of Nest
9. Enumeration in package.json
10. Translation in all languages for NestJS entry

NestJS Icons - add main Filetypes to NestJS

---

src/icons/fileIcons.ts

Currently, only a full match for `azure-pipelines.yml` matches to the `azure-pipelines` logo. With this change, the user can choose `.yaml` instead of `.yml` as their preferred file ending and still get the same logo.

Map azure-pipelines.yaml to azure-pipelines also in addition to .yml

---

src/icons/fileIcons.ts

Hi,
.env.sample is often use as an alternative to .env.example, so i propose this change to make it have the Tune icon !
Thanks

Add ".env.sample" to the Tune icon

---

src/icons/fileIcons.ts

Some users might have multiple pipeline definitions in their projects. I often see users (including myself) naming them `dev.azure-pipelines.yaml`, `staging.azure-pipelines.yaml` and so on. This change would allow users to do that and still see the azure-pipeline icon.

Add azure-pipeline icon to files ending with *.azure-pipelines.yaml

---

src/icons/fileIcons.ts

Babel now supports [`babel.config.json`](https://github.com/babel/babel/pull/10501#issue-321886740) and [`.babelrc.json`](https://github.com/babel/babel/pull/10783#issue-347179686) as a valid [babel configuration file](https://babeljs.io/docs/en/config-files#supported-file-extensions).

Add json file extension to babel file association

---

src/icons/fileIcons.ts

Resolves  https://github.com/PKief/vscode-material-icon-theme/issues/708

Add eslintcache

---

src/icons/folderIcons.ts

I've noticed a few repos that keep code in a folder called code

add 'code' to 'folder-src' icon

---

src/icons/fileIcons.ts

for those of us that use `nodenv` out there those configuration files should be included in the nodejs icon association as they are equally similar to an `.nvmrc` file in functionality

added .node-version filetype to nodejs association

---

src/icons/fileIcons.ts

These are used by the [`dotenv-extended`](https://www.npmjs.com/package/dotenv-extended) package (~25k weekly downloads, 4 years old).

feat(files): add .env.schema and env.defaults

---

src/icons/fileIcons.ts

Hi 👋 I work on a lot of Firebase projects and am always sad seeing various configuration files like `firestore.rules` with no icon. This PR adds support for some of the most common Firebase files generated by the Firebase CLI - feel free to remove some like `storage.rules` if you think those are too broad / may be used in a non-Firebase context.

Add additional Firebase filenames

---

src/icons/fileIcons.ts

Supersedes #755 (it was closed because the repository was deleted).

Add CNAME file name to http icon

---

src/icons/fileIcons.ts

Modules are more and more use in NodeJS, in particular with the new "type": "module" option in package.json. Only, ESLint doesn't accept modules as configuration files, so we have to explicitly specify the config file as a commonJS module.
You can see [here](https://eslint.org/docs/user-guide/configuring#configuration-file-formats-1) that it is a valid ESLint config extension.

Add .cjs extension to ESLint icon

---

src/icons/fileIcons.ts

Associate docker icon to Dockerfile.prod and Dockerfile.production, I think that is important because prod/production no have an icon and Dockerfile.prod and Dockerfile.production stay without an icon ( unknown icon )

Associate docker icon to Dockerfile.prod and Dockerfile.production

---

src/helpers/customIcons.ts
src/helpers/fileConfig.ts
src/icons/generator/fileGenerator.ts
src/icons/generator/folderGenerator.ts
src/icons/generator/iconOpacity.ts
src/icons/generator/iconSaturation.ts
src/icons/generator/jsonGenerator.ts
src/icons/generator/languageGenerator.ts

This pull requests fixes #827 and allows the extension to update the saturation and the opacity of custom SVG files.

Adjust saturation and opacity for custom file icons

---

src/icons/fileIcons.ts

- Added "COPYING", which is, along with "LICENSE" and "LICENCE", a common generic filename for license files.
- Removed the "unlicense" filename, which is specific to a single license, and by itself does not guarantee that the file is actually a license. This reverts #474. Here are some examples of false positives:
- [`_licenses/unlicense.txt` at github/choosealicense.com](https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/unlicense.txt)
- [`src/.../SPDX/Unlicense` at fossology/fossology](https://github.com/fossology/fossology/blob/master/src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Unlicense)
- [`website/Unlicense` at spdx/license-list-data](https://github.com/spdx/license-list-data/blob/master/website/Unlicense)

Make filenames for license files more generic

---

src/icons/fileIcons.ts

`dune-workspace` wasn't included in #707.
For reference: https://dune.readthedocs.io/en/stable/dune-files.html#dune-workspace.

Add dune-workspace file to dune file icons

---

src/icons/fileIcons.ts

For reference on `cabal.project` file: https://cabal.readthedocs.io/en/3.4/cabal-project.html.

Add cabal.project file to cabal file icons

---

src/icons/folderIcons.ts

Hi all! 👋 
During the operating Terraform creates `.terraform` directory so I decided there definitely should be a support for such folder 🙂

Add '.terraform' folder name support

---

icons/proto.svg
src/icons/fileIcons.ts
src/icons/languageIcons.ts

Added a custom icon for .proto files, inspired by google's icon for protocol

Add proto icons (#902)

---

CONTRIBUTING.md

Added a couple tips in Contributor guide to help n00bs like me to create better SVG icons.

Update Contributor guidance with a couple suggestions

---

src/icons/fileIcons.ts

SvelteKit has been using `svelte.config.cjs` for it's config file, so this shows it with a svelte icon as well as `svelte.config.js`.

Show `svelte.config.cjs` as svelte file

---

src/icons/folderIcons.ts

Simply add `inc` to the list of folder names that use `folder-include` icon.

add 'inc' to 'folder-include' folder names

---

icons/gitpod.svg

Gitpod was redesigned on [April 8, 2021](https://www.gitpod.io/blog/next-chapter-for-gitpod): the logo should be updated.
Source of the icon: www.gitpod.io/svg/logo-textless.svg

Update Gitpod icon

---

src/icons/fileIcons.ts

I believe `.env.template` is reasonable and good name for .env files and in some cases might be more suitable than .sample, .defaults, .example, .schema etc.

added .env.template to .env recognized filenames

---

icons/hex.svg
src/icons/fileIcons.ts

This closes #1061
---
A new icon for `.dat`, `.hex` and `.bin` files.
Inspired by the fact that these files can be opened/edited with [Hex Editor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor), I think the '0x' icon makes sense.
I extracted the icon from [Material Design Icons](https://materialdesignicons.com/) and adjusted a little for pixel-correction.

Add Hex file icon

---

src/icons/fileIcons.ts

Applies Webpack icon to webpack.mix.js. Requested in #997.
Does the Webpack icon look better with the white fill?

Add webpack.mix.js icon association

---

src/icons/fileIcons.ts

The `artisan` script is used by Laravel's Artisan CLI for application build. [Sample](https://github.com/laravel/laravel/blob/8.x/artisan).

Add artisan icon association

---

src/icons/fileIcons.ts

Since the storybook added full support for svelte and has added support for CSF we can create stories using `stories.svelte` format to stick to the svelte style of creating components.

Adding new extension of storybook CSF format for svelte

---

src/icons/fileIcons.ts

Associated with `vetur.config.js` and `vetur.config.ts`. Requested in #997.

Add vetur.config.* icon associations

---

src/icons/fileIcons.ts

Located in Gutenberg project: https://github.com/WordPress/gutenberg/tree/trunk/packages/scripts/config
CC @PKief

Add eslint config for markdown documentation

---

src/icons/fileIcons.ts

Enable JSDocs to be linted with ESLint and is used in core WordPress software development repo.
Ref: https://github.com/WordPress/wordpress-develop

Add ESLint config for JSDoc documentation

---

src/icons/fileIcons.ts

Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file

Add XML support for PHP_CodeSniffer ruleset file

---

src/icons/folderIcons.ts

This folder is used to store dummy sample data for WordPress plugins.
Ref: https://github.com/woocommerce/woocommerce

Add support for `sample-data` folder

---

src/icons/folderIcons.ts

This is also the WordPress folder to store plugins and themes SVN assets during development.

Add folder `.wordpress-org` support

---

src/icons/fileIcons.ts

The husky tool is great for git hooks and those files are shell scripts. Since `sh` is denoted for the console icon we can adapt those for git hooks because they are shell scripts overall. On a new git init browse `.git/hooks` folder and those all are shell scripts although there is no extension `sh`.
Ref: https://github.com/wpeverest/everest-forms/tree/develop/.husky
CC @PKief

Add support for git-hooks as console file icon

---

src/icons/fileIcons.ts

Adds mapping for `tsconfig.build.json` and `jest-e2e.json`, used by Nest.js template:
https://github.com/nestjs/schematics/tree/master/src/lib/application/files/ts

Add Jest and TSConfig from Nest template

---

src/icons/folderIcons.ts

It denotes the collection of patches and file extension `.patch` has git icon https://github.com/PKief/vscode-material-icon-theme/blob/bd1142e717d4211819fd04f75ab5052041209e3d/src/icons/fileIcons.ts#L514
Ref for the patches directory: https://github.com/WordPress/gutenberg/tree/trunk/patches
CC @PKief

Allow folder icon for patches collection

---

src/icons/folderIcons.ts

Go pkg folder routes to packages icon by default now.
Closes #1251

Routes pkg to packages icon by default (4 Go devs)

---

src/icons/fileIcons.ts

According to https://github.com/renovatebot/renovate/pull/7423, `renovate-config.json` is a valid config file name for organization-wide presets, so I think it should be added here to reflect that.

Add "renovate-config.json" to renovate filenames

---

src/icons/fileIcons.ts

Need file icon for go.work (Go workspace feature)
It will be released in go1.18 version 
[go.work proposal](https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#proposal-the-file)

fileicon added for go.work file

---

src/icons/fileIcons.ts

`pom.xml` is the file name for the maven Project Object Model, and is in every maven project. As the maven icon already exists, applying it to `pom.xml` makes sense.

Add `pom.xml` to maven files

---

src/icons/folderIcons.ts

Currently, the svelte logo and color only runs for a folder called 'svelte'. However, it is rare for a folder to be called 'svelte'. However, now that Svelte-kIt is gaining in popularity, you will have many folders called '.svelte-kit' as this is the build folder for Svelte Kit. 
Solves: https://github.com/PKief/vscode-material-icon-theme/issues/1404
P.S. Thank you for this project. It is fun and really awesome.

Add Svelte-Kit to be included with the folder-svelte.

---

src/icons/folderIcons.ts

While .firebase is the configuration folder for firebase, it is common for projects that use firebase to have a folder called "firebase" that contains code for the authentication, firestore code and other utilities.  
Again, thank you for making all the icons and folders look awesome!

Add firebase as a folder name 

---

src/icons/fileIcons.ts
src/icons/folderIcons.ts

This improves support for Makefiles by using the icon in more contexts where it is applicable
`.mk` files, `Kbuild` and `GNUMakefile` are now all highlighted
In the [kernel docs](https://www.kernel.org/doc/html/latest/kbuild/modules.html) for Kbuild
> The above line can be put in either a “Kbuild” file or a “Makefile.”
According to GNU Make's [manual](https://www.gnu.org/software/make/manual/make.html)
> By default, when make looks for the makefile, it tries the following names, in order: GNUmakefile, makefile and Makefile.
In this [SO](https://stackoverflow.com/questions/57228873/the-difference-between-mk-file-and-makefile) answer
> The .mk extension is a more or less standard extension for make files that have other names than the defaults.

Improve range of language `Makefile`

---

src/icons/fileIcons.ts
src/icons/languageIcons.ts

Hello,
I suggest psv (Pipe Separated Values) should be rendering the table icon.
As pipes are not often used in the data, .psv files are useful for this type of structure.
Thanks

feat: psv alias

---

src/icons/fileIcons.ts

This PR simply add file name `commit-msg` to the patterns to display the `console` icon. 
This name aligns with others already listed, commonly used in [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) management libraries like `hysky` (JS). So this PR should reinforce consistency within files with the same type and nature.

Add file name `commit'msg` to display `console` icon

---

src/icons/folderIcons.ts

As per [Gulp Docs](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#splitting-a-gulpfile), every file name is also a valid folder name if it contains an index file.

Add gulpfile.ts etc. as folder names

---

src/icons/fileIcons.ts

This PR adds support for the `graphqlrc.cjs` file.
Closes: #1502

feat: add support for the graphqlrc.cjs file

---

src/icons/fileIcons.ts

Macro-enabled excel format. closes #1493
Though i was wondering: would it be better to make it a specific icon for macro enabled sheet as a spinoff of the table icon?
Maybe by adding the "Script" material icon to the corner.

Associate XLSM with "Table" icon

---

src/icons/fileIcons.ts

Now that Playwright supports component testing
(https://github.com/microsoft/playwright/releases/tag/v1.22.0), this
commit adds the canonical config filenames. It also includes the '.mjs'
extension.

feat: Support Playwright component test config files

---

src/icons/fileIcons.ts

I was unable to find a template to use, so forgive me if I'm not following the correct format. The link below provides information on `go.work.sum`. It should have been added with `go.work` back in February.
https://go.googlesource.com/proposal/+/master/design/45713-workspace.md#files

feat: add go.work.sum to list of go-mod files

---

src/icons/fileIcons.ts

As of Cypress 10.x E2E specs have the "e2e.cy.ts" file extension.
To make Material Icon detect these as E2E Files and not as plain .ts Files I added the cypress specific handle to fileIcons.ts
Please review

Adds Cypress 10.x e2e extension

---

src/icons/fileIcons.ts

In my last PR, #1541, I mistakingly forgot to add support for `.d.cts` and `.d.mts` files as well.
Changes made in this PR will provide support for said files.

Add Support for `.d.cts` and `.d.mts` Files

---

src/icons/fileIcons.ts

- Add missing js extension in Cypress fileNames
- Reference "https://docs.cypress.io/guides/references/migration-guide#Configuration-File-Changes"

[Add] Cypress file name "cypress.config.js" in fileIcon.ts

---

src/icons/folderIcons.ts

This PR adds `__integration-test__` and `__integration-tests__` folder names to the `folder-coverage` icon.

fix: added integration-tests folder

---

src/icons/fileIcons.ts
src/icons/languageIcons.ts

[WGSL](https://gpuweb.github.io/gpuweb/wgsl/) is a shader language, like GLSL or HLSL, but more cross-platform, built for [WebGPU](https://en.wikipedia.org/wiki/WebGPU). I just added it as an extension for shaders.

feat: Added `wgsl` extension

---

src/icons/fileIcons.ts

feat: add web and webworker to tsconfig

---

src/icons/fileIcons.ts

fix: add support to gatsby-config.ts

---

src/icons/fileIcons.ts

Adds `.stylelintcache` to list of stylelint names.
This file-ending corresponds to the default filename for cache files created from running stylelint with flag `--cache`.
More info in their docs: https://stylelint.io/user-guide/usage/options/#cache

Adds default filename for stylelint cache file

---

src/icons/fileIcons.ts

Add Gatsby icon to newly supported typescript files.
- https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#gatsby-browsertsx--gatsby-ssrtsx
- https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#gatsby-configts
- https://www.gatsbyjs.com/docs/how-to/custom-configuration/typescript/#gatsby-nodets

feat: Add support for Gatsby config typescript files

---

src/icons/fileIcons.ts

Added file extension associations for docker-compose in response to #1705 for *.docker-compose.yaml and *.docker-compose.yml to receive the docker icon

Added file association to docker-compose file extension

---

src/icons/fileIcons.ts

Associate `.mcpack` and `.mcaddon` files with Minecraft file icon

---

src/icons/fileIcons.ts

Currently the icon `dependabot` is only mapped to the file extension 
`dependabot.yml`, but Dependabot supports both `.yaml` and `.yml`. 
Tested this personally and it is also documented in various issues in the 
Dependabot repos. For example [here](https://github.com/dependabot/feedback/issues/874).
Fixes <https://github.com/PKief/vscode-material-icon-theme/issues/1745>

feat(dependabot): Add missing filename dependabot.yaml

---

src/i18n/lang-en.ts

This PR suggests changes to the wording of the error messages when the user attempts to set the values for Opacity or Saturation. The previous wording didn’t make it clear, imo, that the value can be a floating-point number. I went to experiment with these settings and initially thought I could only enter a `1` or a `0` (then wondered why they weren’t Boolean).

change error messages for Opacity and Saturation (value should be float)

---

README.md
src/i18n/lang-en.ts

This PR sets the wording of Toggle Explorer Arrows to be more explicit. It also makes minor clarifying changes to wording of some descriptions in the Commands section of README.md.
Successfully merging it would require re-doing the Commands screenshot at
https://github.com/PKief/vscode-material-icon-theme/blob/5e57ec33d3402f325b3e711a6eb34bc3b90c2b1c/README.md?plain=1#L169

harmonise/clarify wording of Toggle Explorer Arrows

---

src/icons/fileIcons.ts

A very simple PR to add [nushell](https://github.com/nushell/nushell)'s `nu` files to the `console` family
- **Before**:
- **After**:

feat: 🎨 add console icon for nushell

---

src/icons/fileIcons.ts

Icon already supported for `.graphqlrc.cjs`, but not for `graphql.config.cjs`, according [graphql config docs](https://the-guild.dev/graphql/config/docs#graphqlconfigjs-or-graphqlrcjs) they are same

Add .cjs extension to `graphql.config`

---

src/icons/fileIcons.ts

According [plop docs](https://plopjs.com/documentation/#3-create-a-plopfilejs-at-the-root-of-your-project) plopfile has support for `.cjs` and `.mjs` extensions

Add .cjs and .mjs extensions to `plop` fileNames

---

src/icons/fileIcons.ts
src/icons/languageIcons.ts

Added extra extension to godot-assets icon to handle a typical [GDNative file structure](https://docs.godotengine.org/en/stable/tutorials/scripting/gdnative/gdnative_cpp_example.html)

Expand godot-assets associations

---

src/icons/fileIcons.ts

Gatsby 5.3+ officially supports ESM with the `gatsby-config` and `gatsby-node` files, but they require an `mjs` extension.
Sources:
- https://www.gatsbyjs.com/docs/reference/release-notes/v5.3/#es-modules-esm-in-gatsby-files
- https://github.com/vscode-icons/vscode-icons/pull/3204

Gatsby - add new supported file extensions

---

src/icons/fileIcons.ts

The config file can be overrides with `-c, --config` option.
Using a `.mjs` config file let Node treating it as an ECMAScript module where you can use ESM syntax rather than set `"type": "module"` in `package.json`.
Refs:
- [Configuration File Resolution](https://eslint.org/docs/latest/use/configure/configuration-files-new#configuration-file-resolution)

feat: enhance ESLint flat config support

---

src/icons/fileIcons.ts

Need to support `tsconfig.paths.json` file to have the TSConfig icon. This file is useful to declare the `paths`:
```json
{
"compilerOptions": {
"paths": {
"@/utils/*": ["src/utils/*"],
"@/constants/*": ["src/constants/*"],
"@/models/*": ["src/models/*"],
"@/interfaces/*": ["src/interfaces/*"],
"@/validators/*": ["src/validators/*"],
"@/pipes/*": ["src/pipes/*"]
}
}
}
```

feat: support TSConfig icon for paths file

---

src/icons/fileIcons.ts

Support an additional file name for semantic release icon: `release.config.cjs`.
This file name format is supported out of the box by semantic release.
That means, it detects it automatically and we don't need to declare something like `... -c ./release.config.cjs`

feat: support CommonJS file for semantic release

---

package.json

Update the structure of the npm module to only include necessary parts of the icon theme (without the source code which is only needed for the VS Code extension):

Update package structure of npm module

---

src/icons/folderIcons.ts

Adding the plural version of word "store" to cover architectures that are based on multiple stores (like `zustand`, for React).

Add "stores" (plural) to folder name

---

src/icons/fileIcons.ts

Determine that `nginxconfig` should be changed to `nginxconf` based on the following content.
https://github.com/joedeandev/prettier-plugin-nginx/commit/a547fafa62ca7986f1fde2fda31758a64d983ad3
https://github.com/joedeandev/prettier-plugin-nginx/blob/b3c840f4bac1373c2dc984825e3dad3308fcbcbe/src/index.ts#L84

fix: `nginx` file extensions typo

---

src/icons/fileIcons.ts

This adds the git icon to `.keep` files. Are there any other git files that are missing? 
Should I also add `.gitpreserve`?

Add git icon to .keep

---

src/icons/fileIcons.ts

Associate `.tfbackend` files with Terraform

---

src/icons/fileIcons.ts
src/icons/languageIcons.ts

- Add dockercompose language id to docker icon
- Remove yml and yaml extensions from file icon association as they will also detected via language id automatically and will not produce a conflict with the `compose.*.yaml` files
Locally tested and it works automatically:
If the automatic detection might not work for some users, they can add this config to their user or workspace settings and it will force VS Code to apply the language id to these files names (interestingly here VS Code supports the glob pattern):
```json
"files.associations": {
"compose.*.yaml": "dockercompose"
}
```
And then this extension finally maps the icon to the language id and applies it to all files which are associated with this id.

[Icon Request] Add icon association to dockercompose language id

---

src/icons/languageIcons.ts

Associate following language ids with yaml icon:
- github-actions-workflow
- jinja-yaml
- spring-boot-properties-yaml
Closes #2064

Add missing language ids for yaml icon

---

src/icons/fileIcons.ts

This fixes the definition of stylelint files with the mjs extension as just js files.

Added mjs extension for stylelint

---

src/icons/folderIcons.ts

`protobuf` / `protos` are commonly used names alongside `protobufs`/`proto` 
(See https://github.com/protocolbuffers/protobuf/tree/main/src/google/protobuf)

chore: add "protobuf" to proto folder names

---

src/icons/folderIcons.ts

Associates `photo`, `photos`, `photograph`, and `photographs` folder names with the same icon as `pic`, `pics`, `picture`, and `pictures`.

add photo (and variants) to folderIcons.ts

---

src/icons/fileIcons.ts

Nuxt 3 generates a separate tsconfig file for its server:

feat: add `tsconfig.server.json` to file names

---

src/icons/fileIcons.ts

Add postcss support for `.mjs`

feat: add postcss .mjs extension support

---

src/icons/fileIcons.ts

Add commitlint `.mjs` extension support
It is in the supported config files
https://commitlint.js.org/reference/configuration.html#config-via-file
```diff
.commitlintrc
.commitlintrc.json
.commitlintrc.yaml
.commitlintrc.yml
.commitlintrc.js
.commitlintrc.cjs
+.commitlintrc.mjs
.commitlintrc.ts
.commitlintrc.cts
commitlint.config.js
commitlint.config.cjs
+commitlint.config.mjs
commitlint.config.ts
commitlint.config.cts
```

feat: add commitlint .mjs extension support

---

src/icons/fileIcons.ts

The [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci/tree/main) now [supports](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#:~:text=.lighthouserc.cjs,lighthouserc.cjs) the .cjs file extension.

feat: add lighthouserc .cjs extension support

---

.editorconfig
.gitattributes

While format/eol desyncs haven't been a problem in the past, this is a safeguard to ensure it stays that way. Also, explicitly excludes `svg` files from getting a final newline, as those are meant to be saved in a compressed format.

feat: Add `.editorconfig` and `.gitattributes`

---

src/icons/folderIcons.ts

Gives the linux/windows/macos folders a bit more wiggle-room in terms of use by adding extra platform names. The names aren't used anywhere else in the repo so there's no risk of overlapping existing elements.

Add aliases for platform folders

---

.eslintrc.json
.prettierrc
tsconfig.json

Further ensure line endings come out as `lf` by addressing some settings missed in #2290

Add some missed attribute options

---

src/icons/fileIcons.ts

Biome config file can be both `biome.json` and `biome.jsonc` (JSON with comments)
Reference: <https://biomejs.dev/guides/getting-started/#configuration>

feat: support biome.jsonc

---

.devcontainer/devcontainer.json

I've added a `devcontainer.json` to quickly start development on **GitHub Codespaces** so that dependencies are automatically installed when the Codespace is created.
What's special about **Codespaces** is that you can **instantly** start development on **any** project
But in this case it won't be instant, because it has to install dependencies before opening, and that takes time, so I advise you to enable **prebuilds** for **Codespaces** in the repository settings, this will allow developers to skip installing dependencies and start development in a completely ready-to-use environment, including with previously installed **vscode** extensions
Also, I strongly recommend adding the "[**Svg Preview**](https://marketplace.visualstudio.com/items?itemName=SimonSiefke.svg-preview)" extension to …

Added `devcontainer.json`

---

src/icons/generator/fileGenerator.ts
src/icons/generator/folderGenerator.ts
src/test/spec/icons/fileIcons.spec.ts
src/test/spec/icons/folderIcons.spec.ts

Allow interoperability between icons cloned by the extension and custom user associations, so that cloned icons can be assigned via `material-icon-theme.[files|folders].associations` setting.
Ref: https://github.com/PKief/vscode-material-icon-theme/pull/2314#issuecomment-2104897492

fix: 🚑 interop between cloned icons and user associations

---

README.md

Replaced the dead link to the list of material palette colors, with the correct one.

fix: dead README.md link

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/color-check.yml
.github/workflows/icon-review.yml
.github/workflows/pr-closed.yml
.github/workflows/release.yml
.vscode/settings.json

I decided to look at the diff for 314aba7ba73d32293cf4608e0319beab5f2d4c18 and noticed it touched automated publishing. This is minor improvement to that flow that allows consumers to verify that the code did come from github actions, and wasn't created locally with a backdoor. This can prevent certain _very_ specific supply-chain attacks.
I don't know why anyone would care, but someone probably will eventually complain, so it's better to do it now than latter. Although, in all seriousness, there are much better vectors for breaking into builds, and this doesn't help much without SHA pinning (I can do as well that if you'd like). Nevertheless, It doesn't hurt anything and I already had the the tab open 🙃

chore: provenance

---

.github/workflows/release.yml

https://github.com/material-extensions/vscode-material-icon-theme/blob/9b7100ed2c206384809b92d8b1c4705f7ce31506/.github/workflows/release.yml#L29-L34
Not persisting credentials while checking out the repository in the `release.yml` action will make the `git push` step to fail with:
```
fatal: could not read Username for 'https://github.com/': No such device or address
```
See a failing example [here](https://github.com/lucodear/lucodear-icons/actions/runs/9786548996/job/27021620014)
Deleting that option [fixed it](https://github.com/lucodear/lucodear-icons/actions/runs/9787261151) and that's what I'm doing in this PR, but there might be another way.
Pinging @lishaduck here for a review (creator of #2365) because he knows much more about github actions than me. Maybe he knows a better way.

fix: 🚑 error with persist-credentials=false in the release action

---

icons/folder-jupyter-open.svg
icons/folder-jupyter.svg
src/icons/folderIcons.ts

Add folder icons for Jupyter

---

.github/workflows/icon-review.yml

I noticed that the image preview comments got really long in #2383, so I fixed it.
If you'd like to prevent another #2385, I guess I could make a random edit, check it works, then revert it.

Replace generated image previews instead of creating new ones

---

.github/workflows/icon-review.yml

> [!NOTE]
> ### tl;dr
> 
> adds a link in the "preview comment" to a tool that lets you see how the icon fits in
> a 16x16 grid
Hi!
A while ago, my team and I developed a simple internal tool to check if the icons added by a PR fit ok in a 16x16 pixel grid. A few days ago, we decided to make it open source, adapt it to work with any github repo and hosted it on the web.
Basically, what the web app does is query the GitHub API to get the SVG files added or modified by a PR and display them with an overlaid grid to quickly see if there are any issues. Nothing too fancy, but it ended up being quite useful for us.
This PR simply adds a link referencing the webapp rout to the current PR.
Here's an example:
https://pixp.lucode.ar/material-extensions/vscode-material-icon-theme/pull/2382
The …

ci: 🔄 add link to check pixel perfectness in preview comment

---

src/core/icons/fileIcons.ts

Files with the extension `.xlf` are localization files, so I think it would be appropriate to use the `i18n` icon for them
**Wiki**: https://en.wikipedia.org/wiki/XLIFF

Added icon for `xlf` files

---

.github/FUNDING.yml

**GitHub** provides the option to add a custom link for [**Buy Me A Coffee**](https://buymeacoffee.com/), then the logo will appear on the left
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files

Added separate Buy Me a Coffee link in `FUNDING.yml`

---

src/core/icons/folderIcons.ts

Related to #2472
Add an entry for the `lib64` folder in the `folderIcons` array to use the same icon as the `lib` folder.
* Add `lib64` to the `folderNames` array for the `folder-lib` icon in `src/core/icons/folderIcons.ts`.
[Generated with GitHub Copilot Workspace]
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/material-extensions/vscode-material-icon-theme/issues/2472?shareId=7db9e6fa-095f-41cc-8e04-01bc4854fd07).

Add lib64 folder icon

---

.vscodeignore

I used a "_leave what is necessary_" strategy, instead of adding a **large** list of files that do not need to be added to the **extension package** (which increases the **high** probability of unwanted files getting into the package), I wrote down the files that just need to be left, this is a safer practice and in addition, `.vscodeignore` is now clearer
Here is the file tree in the finished package:
```text
INFO  Files included in the VSIX:
material-icon-theme-5.7.0.vsix
├─ [Content_Types].xml 
├─ extension.vsixmanifest 
└─ extension/
├─ .npmignore [0.08 KB]
├─ CHANGELOG.md [172.13 KB]
├─ LICENSE.md [1.05 KB]
├─ README.md [12.38 KB]
├─ logo.png [17.32 KB]
├─ package.json [10.77 KB]
├─ package.nls.cs.json [2.28 KB]
├─ package.nls.de.json [2.32 KB]
├─ package.nls.es.json [3.28 KB]
├─ …
```

Optimized `.vscodeignore`

---

.github/workflows/icon-review.yml

Fixes a regression introduced in #2467 that makes the **review** github action not to update the first comment anymore and create a new one instead.
[See here](https://github.com/material-extensions/vscode-material-icon-theme/pull/2480#issuecomment-2251133809)

fix(ci): 🚑 first preview comment not being updated

---

icons/slint.svg
src/core/icons/fileIcons.ts
src/core/icons/languageIcons.ts

Added `slint` icon for file extension (`slint` and `60`) and language id (`slint`)
Source: https://slint.dev/logo/slint-logo-small-light.svg

Added `slint` icon

---

src/core/icons/folderIcons.ts

Related to #2483
Add `inc64` folder icon to match `inc` folder icon.
* **src/core/icons/folderIcons.ts**
- Add `inc64` to the `folder-include` entry in the `folderNames` array.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/material-extensions/vscode-material-icon-theme/issues/2483?shareId=2900e6ec-2621-427e-be90-8f2f6bd9ff68).

Add inc64 folder icon

---

src/core/models/icons/defaultIcon.ts
src/core/models/icons/files/fileIcon.ts
src/core/models/icons/folders/folderIcon.ts
src/core/models/icons/languages/languageIdentifier.ts
src/core/models/icons/patterns/patterns.ts

Improved Markdown formatting for better understanding of tooltips

Improved hint comments

---

.github/workflows/icon-review.yml

The command `grep -v '^../main/'` should filter out all files coming from the main repo so that only the file changes from the fork should be shown in the icon review.

Improve icon review workflow

---

CONTRIBUTING.md

Related to #2504
Update the URL for the color palette in `CONTRIBUTING.md` to point to the correct URL.
* Change the URL on line 122 from `https://pkief.com/material-color-converter/` to `https://pkief.github.io/material-color-converter/`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/material-extensions/vscode-material-icon-theme/issues/2504?shareId=78016583-ff8b-4827-8deb-d62568711afb).

Fix URL in CONTRIBUTING.md

---

src/core/icons/fileIcons.ts

Closes #626
Associate the `.vhdl` file extension with the same icon as `.v` and `.vhd` files.
* Add `vhdl` to the `fileExtensions` array for the `verilog` icon in `src/core/icons/fileIcons.ts`.

Add VHDL file icon association

---

src/core/icons/folderIcons.ts

Closes #2527
Add 'devtools' to the folder names associated with the 'tools' icon.
* Modify `src/core/icons/folderIcons.ts` to include 'devtools' in the `folderNames` array for the 'tools' icon.

Include 'devtools' in the folder-icon for 'tools'

---

.github/pull_request_template.md

Hi, I fixed broken links in `pull_request_template.md`.
Relative paths to contribution guide lines and code of conduct make 404 NOT FOUND ERROR.
So I fixed it using URI not relative paths.

docs: 📝 fix broken links in pull_request_template

---

src/core/icons/fileIcons.ts

Hi😊, I added `.markdownlintignore` file into fileNames list which is used by [markdownlint](https://github.com/DavidAnson/markdownlint).
`.markdownlintignore` uses the same icon such as markdownlint(![image](https://github.com/user-attachments/assets/1b7d7d61-ed93-4c1d-ad0f-8da8eac55a4f)). So there is no need to add a new file icon.
This file is mentioned in official README of [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli?tab=readme-ov-file#ignoring-files). (I added a screenshot below.)

feat: ✨ .markdownlintignore file icon

---

src/core/icons/fileIcons.ts

Hi, I added `.clang-format-ignore` file into fileNames list which is used by [clang-format](https://clang.llvm.org/docs/ClangFormat.html).
It uses the same icon such as `.clang-format`. So there is no need to add a new file icon.
This file is mentioned in [here](https://clang.llvm.org/docs/ClangFormat.html#clang-format-ignore). (I added a screenshot below.)

feat: ✨ .clang-format-ignore file icon

---

.github/ISSUE_TEMPLATE/1-icon-request.yml

Fixes #2588
Update the icon request issue template to allow creating an issue by selecting only the 'Folder' option without requiring the 'File' checkbox.
* Remove the `required: true` attribute for the `File` checkbox in the `.github/ISSUE_TEMPLATE/1-icon-request.yml` file.
* Add a `validations` section with `required: true` for the `icon-type` checkboxes to ensure at least one option is selected.
Based on documentation:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#example-of-bodyi-options-must-not-include-the-reserved-word-none-error

Fix icon request template

---

src/scripts/module/prepare.ts

Remove unnecessary fields from package json for npm bundle.
Closes #2598.

Remove vscode specific fields from module's package json

---

src/core/icons/fileIcons.ts

Adds color variants to the Svelte icon for `.svelte.js` and `.svelte.ts` files
Closes https://github.com/material-extensions/vscode-material-icon-theme/issues/2599

Add .svelte.js and .svelte.ts color variants

---

src/core/generator/languageGenerator.ts

Ensure that language icon definitions support different icons for light and dark background themes.

Fix light mode for language ids

---

src/core/icons/fileIcons.ts

Added `gltf` and `glb` to the 3d file extensions list

Add icon association for gltf and glb files

---

.github/workflows/icon-review.yml

The `pixp.lucode.ar` domain will stop working in about 3 months (I'm progressively moving my domains to `.tech`, `.dev` and `.com`), so this PR changes the url of the pixp link comment (preview in pull requests) to `pixp.pages.dev/...`, which will be alive forever, since it's the default cloudflare domain.
Example of generated url after this change:
https://pixp.pages.dev/material-extensions/vscode-material-icon-theme/pull/2270

ci: update pixp url in icon-review.yml

---

.gitattributes
.github/ISSUE_TEMPLATE/1-icon-request.yml
.github/ISSUE_TEMPLATE/2-bug-report.yml
.gitignore
.vscodeignore
material-colors.yml
svgo.config.js

chore(docs): add useful comments and update issue templates

---

.github/pull_request_template.md
.github/workflows/pr-title.yml
CONTRIBUTING.md
commitlint.config.js

As we're planning to change the way how we're generating the changelog in the future, we want to have semantic PR titles. While merging a PR we're squashing the commit history of the PR to a single commit on the target (main) branch. The squashed commit will be named after the PR title. That's why this workflow is ensuring that a PR title follows the conventional commit style.
Once we get an invalid PR title the pipeline fails:

ci: Add workflow to check PR title following conventional commit

---

.github/workflows/build.yml
.github/workflows/color-check.yml
.github/workflows/release.yml

Checkouts now load only the current commits instead of loading the entire commit history
See https://github.com/actions/checkout#:~:text=Only%20a%20single%20commit%20is%20fetched%20by%20default%2C%20for%20the%20ref/SHA%20that%20triggered%20the%20workflow.%20Set%20fetch%2Ddepth%3A%200%20to%20fetch%20all%20history%20for%20all%20branches%20and%20tags

perf(workflows): ⚡optimize checkout steps

---

src/core/icons/fileIcons.ts

Fixes #2692.
Apologies for not double-checking this behavior in my original PR, I hadn't been using files matching that glob pattern and neglected to check.
As you can see this change will fix the bug:

fix: Garden file extensions

---

src/core/icons/fileIcons.ts

See https://wiki.haskell.org/Literate_programming#Haskell_and_literate_programming
> In haskell, a literate program is one with the suffix `.lhs` rather than `.hs`.
- Add `'lhs'` to Haskell's `fileExtensions`

feat: show Haskell icon for `.lhs` files

---

icons/toml.svg
icons/toml_light.svg
src/core/icons/fileIcons.ts
src/core/icons/languageIcons.ts

Icon from: <https://toml.io>
I think it might be necessary to change the color of that black `T` in the middle (to a lighter gray? maybe) to fit dark backgrounds.
This pr resolves #361 and is related to #362

feat: add toml icon

---

src/core/icons/fileIcons.ts

Supplement to [#198](https://github.com/material-extensions/vscode-material-icon-theme/pull/1898).
add [`.hgtags`](https://wiki.mercurial-scm.org/Tag#What_if_multiple_lines_with_different_revisions_use_the_same_tag_name_in_.hgtags.3F) icon.

feat: add .hgtags icon

---

src/core/icons/fileIcons.ts

Adds `.dev.vars` to the association list of the env file icon.
`.dev.vars` is used to set environment variables for local development of cloudflare workers (see [here](https://developers.cloudflare.com/workers/configuration/environment-variables/#:~:text=For%20local%20development%20with%20wrangler%20dev%2C%20variables%20in%20wrangler.toml%20are%20automatically%20overridden%20by%20any%20values%20defined%20in%20a%20.dev.vars%20file%20located%20in%20the%20root%20directory%20of%20your%20worker.%20This%20is%20useful%20for%20providing%20values%20you%20do%20not%20want%20to%20check%20in%20to%20source%20control.))

feat: add `.dev.vars` association to `env` file icon

---

src/core/icons/fileIcons.ts

Adds `.tool-versions` association. Used in [asdf](https://github.com/asdf-vm/asdf) as a config file to manage multiple runtime versions.
https://asdf-vm.com/manage/configuration.html#tool-versions

feat: ✨ add icon for `.tool-versions` file

---

material-colors.yml

* Updated `material-colors.yml` to exclude specific icon files from being checked.

chore: add some icons to exclusion list

---

.github/workflows/close-stale-issues.yml

Closes inactive issues after some time. Some issues are marked as ["info-needed"](https://github.com/material-extensions/vscode-material-icon-theme/labels/info-needed) and "invalid". As there's no update or any further comment in this issue, then we should close these issues as they cannot be proceeded. This workflow checks every nigth, if we have issues which are stale and can be closed.

chore(workflows): :construction_worker: Add workflow to close inactive issues

---

src/core/generator/clones/clonesGenerator.ts
src/core/generator/fileGenerator.ts
src/core/generator/folderGenerator.ts
src/core/generator/languageGenerator.ts
src/core/tests/icons/fileIcons.test.ts
src/core/tests/icons/folderIcons.test.ts
src/core/tests/icons/languageIcons.test.ts

If a base icon of a configured clone is initially disabled via icon package, then the creation of the clone icon is not working, even when the icon pack is enabled.
The following code snippets demonstrate the edge case in which the clone functionality is not properly working. We add a new folder called `folder-bug` which should clone from the base folder `folder-base`:
```ts
{
name: 'folder-bug',
folderNames: ['bug'],
clone: {
base: 'folder-base',
color: 'light-blue-700',
},
},
```
The `folder-base` icon is not enabled all the time, but only if the `IconPack.React` is enabled:
```ts
{
name: 'folder-base',
folderNames: ['base'],
enabledFor: [IconPack.React],
},
```
We keep the icon pack configuration at its default value:
```json
{
"material-icon-theme.activeIconPack": "angular"
}
```
The …

fix: :bug: fix issue with disabled base icons of clones

---

.github/actions/update-status-label.sh
.github/workflows/build.yml
.github/workflows/color-check.yml
.github/workflows/pr-title.yml

Add steps to workflows to manage labels based on workflow results.
This will provide a convenient understanding of the problem with PR
* **Color Check Workflow**:
- Add permission to write pull requests.
- Add step to manage `invalid-colors` label based on color check result.
* **Build Workflow**:
- Add permission to write pull requests.
- Add step to manage `invalid-build` label based on build result.
* **PR Title Workflow**:
- Add step to manage `invalid-title` label based on PR title check result.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/material-extensions/vscode-material-icon-theme/pull/2785?shareId=a61e4790-92ed-4501-9145-7bcd0ba6d81e).

feat(ci): 🔖 add appropriate labels to PRs with failed checks

---

.vscode/settings.json

* Added `files.readonlyInclude` for `bun.lock` to prevent accidental modifications.
* Improved settings structure for better readability.

chore: 🔒 make `bun.lock` readonly

---

.github/FUNDING.yml
.github/labeler.yml
.github/workflows/build.yml
.github/workflows/close-stale-issues.yml
.github/workflows/color-check.yml
.github/workflows/icon-review.yml
.github/workflows/label.yml
.github/workflows/potential-duplicates.yml
.github/workflows/pr-closed.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml

...and make clear the names of the steps in workflows
* Moved `permissions` to the top for a better structure, besides there is no point in setting `permissions` inside `steps`, because we only use one step in the workflow, so it is allowed to apply `permissions` globally.
* Streamlined the structure of GitHub Workflows
* Modified funding configuration format for GitHub.
* Cleaned up unnecessary comments and improved overall readability.

refactor(ci): ♻️ organize the structure of workflows

---

src/core/icons/folderIcons.ts

Hello,  
I’ve added the `websites` folder icon to the `folder-public` list.  
Since the `websites` folder is commonly used in the same way as the `website` folder, I believe it’s better to include `websites` as well.

feat: add `websites` folder icon

---

.github/ISSUE_TEMPLATE/1-icon-request.yml

I saw issue #1260 and whoever created it coolly added an emoji to the icon type selection field, so I think we should add it for better recognition

chore: ✨ use emojis in icon request template for better recognition

---

src/core/icons/folderIcons.ts

Changed  `folderNames: ['directive, directives']` to `folderNames: ['directive', 'directives']`
I was making a list in vscode of the different folders and noticed the mistake that "directive, directives" was one folder name instead of "directive", "directives"

Fix folderIcons.ts

---

icons/uv.svg
src/core/icons/fileIcons.ts

Adds an icon for [uv](https://docs.astral.sh/uv/) config files, based on the uv tool logo.

feat: add uv icon

---

src/core/icons/folderIcons.ts

Add navigation folder icon. I've used a hamburger as it's the typical icon for a menu / navigation.

feat: add navigation folder icon

---

src/core/icons/fileIcons.ts

Added the subtitle icon to Advanced SubStation Alpha (`.ass`) subtitle files.

feat: add the subtitle icon to `.ass` files

---

src/core/icons/fileIcons.ts

Adding the `python-misc` icon to the following Python-adjacent file types:
1. *.egg
2. .coveragerc
3. .coverage
4. .scrapy
5. celerybeat-schedule
6. celerybeat.pid
All of these previously had no icon associated with them.

feat: add support for more Python-adjacent file types

---

src/core/icons/fileIcons.ts

Turborepo now supports JSONC, as documented at <https://turbo.build/docs/reference/configuration>.

feat(icons): add support for `turbo.jsonc` file in turborepo icon

---

src/core/icons/fileIcons.ts
src/core/icons/languageIcons.ts

ArkTS is a superset of TypeScript open sourced by the [OpenHarmony organization](https://en.wikipedia.org/wiki/OpenHarmony) to support the development of the HarmonyOS App. I recently created an [ArkTS VSCode plugin](https://github.com/Groupguanfang/arkTS) that supports the code highlighting and completion of the ArkTS language. 
I love using this material icon theme, There are relatively few people using ArkTS on VSCode at the moment, and there seems to be no official file icon for ArkTS available at the moment. So I simply associated TypeScript icon with ArkTS in a simple way (with just a few minor changes). Hope the author approves this PR🥹Thank you very much indeed🙏

feat: associate the `.ets` and `.d.ets` extensions to typescript icon to support the ArkTS language

---

src/core/icons/folderIcons.ts

This PR updates the `folder-sandbox` icon definition to include plural forms of existing folder names.
Added `sandboxes` and `playgrounds` folder names.

feat: add plural folder names for folder-sandbox icon

---

src/core/icons/folderIcons.ts

Add `song` and `songs` folder to the `audio` folder icon

feat: add song and songs to audio folder icon

---

src/core/icons/folderIcons.ts

add `bench` and `perf` folder names to benchmark folder icon

feat: add bench and perf to benchmark folder icon

---

src/core/icons/fileIcons.ts

Add `supabase.ts` to list of files that appear with a Supabase icon. TypeScript support since icon already appears for `supabase.js`.

feat: add `supabase.ts` to list of supabase icons

---

src/core/icons/folderIcons.ts

add `palette` and `palettes` to theme folder icon

feat: add palette and palettes to theme folder icon

---

src/core/icons/languageIcons.ts

This pull request just associates the Docker icon to the `dockerbake` language ID.

feat: associate Docker icon to `dockerbake` language ID

---

src/core/icons/fileIcons.ts

Adds `.xsh` files (used by the Xonsh shell) to the list of extensions mapped to the existing `console` icon. This is consistent with how other shell script extensions like `sh`, `fish`, and `nu` are handled.

feat: add .xsh to console icon

---

src/core/icons/fileIcons.ts

[Prisma](https://www.prisma.io/) is working on a [new config file standard](https://www.prisma.io/docs/orm/reference/prisma-config-reference), still in early access, but the file name should not change. Therefore, I'm adding this newer file name to the existing Prisma files set to use the respective icon.

feat: add new config file for Prisma

---

src/core/icons/fileIcons.ts

This pull request removes the icon associations for the `.tex` and `.ltx` file extensions to avoid a conflict with the icon assigned to the `latex` language ID.
The issue is that the `.tex` extension is used for both TeX and LaTeX files. However, since an icon was specifically associated with this extension, the icon would always be the same regardless of the language ID.
By removing the icon association from the extension, only the language ID will determine which icon is shown. Since VS Code recognizes the `tex` and `latex` IDs without needing a third-party extension, this should not cause any issues.

refactor: remove icons for `tex` and `ltx` file extensions

---

src/core/icons/fileIcons.ts

Adds `.env.sentry-build-plugin` to the list of recognized filenames for the existing Sentry icon.
This file stores authentication credentials and project metadata for use by Sentry’s official build plugins (Webpack, Vite, esbuild, Rollup, and eventually Turbopack once production plugin support is stable) to enable automated source map uploads.
---

feat(fileIcons): add .env.sentry-build-plugin to sentry icon

---

src/core/icons/languageIcons.ts

Add support for `nginx` language icon id, from the nginx extension

feat: ✨ add nginx to language icons config

---

src/core/icons/folderIcons.ts

Hi! First of all, thank you so much for this great icon theme! 🙂 
This is an extremely simple PR. I just added `vector` to the folder names for the `folder-svg` icon, as I think it would be very nice to have it since it's usually a more generic term to refer to "vector images".
I hope this is useful :) Let me know. Thanks in advance!

feat: use folder-svg icon for folder name 'vector'

---

README.md

It appears that the translation files have been moved to `src/core`.

docs: fix translations path
