fileicons/material-icons.json

`.fsx` - F# Script Files
`.fsi` - F# Signature Files

Add F# icon for `.fsx` and `.fsi` files

---

src/material-icons.json

Add missing webpack.base.js

---

src/i18n/uk.json

Hello! Thank you for the cool icons)
I added my language 😄

add Ukrainian language

---

icons/smarty.svg
src/material-icons.json

Added Smarty (.tpl) icon

---

icons/nunjucks.svg
src/material-icons.json

There doesn't seem to be a universally recognised icon for nunjucks so I made this based on the official website.

Added icon for nunjucks files

---

icons/folder-vue-open.svg
icons/folder-vue.svg
src/material-icons.json

Added vue folder icons

---

package.nls.zh-CN.json

added I18N Simplified Chinese for the entries in the command palette

---

package.nls.ru.json
src/i18n/lang-ru.ts

Updated RU translation

---

src/icons/fileIcons.ts

[ScriptCS](http://scriptcs.net/) is technically C#, same icons should be applied.

Added: csx extension to C#

---

src/icons/fileIcons.ts

👋 This PR add crystal icon for embedded crystal `.ecr` file, its like `.erb` on ruby

Added crystal icon on .ecr ( Embedded Crystal )

---

src/icons/fileIcons.ts

Add [gatsby-browser.js](https://www.gatsbyjs.org/docs/browser-apis/) and [gatsby-ssr.js](https://www.gatsbyjs.org/docs/ssr-apis/)

Add additional gatsby file names

---

src/icons/fileIcons.ts

Supported .env files: https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables

added tune icon to .env file names supported by Create React App

---

icons/folder-vuex-store-open.svg
icons/folder-vuex-store.svg
icons/vuex-store.svg
package.json
package.nls.de.json
package.nls.es.json
package.nls.fr.json
package.nls.json
package.nls.pt-BR.json
package.nls.pt-PT.json
package.nls.ru.json
package.nls.zh-CN.json
src/icons/fileIcons.ts
src/icons/folderIcons.ts
src/models/icons/iconPack.ts

Added icons for vue related files, folders and vue theme.

Add vue and vuex_vuex theme

---

src/icons/fileIcons.ts

Adds mocha file icon to .mocharc[.yaml|.yml|.js|.json|.jsonc]

Adds .mocharc file icon

---

src/icons/fileIcons.ts

Example: https://github.com/Logerfo/csharp-colors/blob/master/UNLICENSE

Added certificate icon to unlicense files

---

src/icons/fileIcons.ts

Add `.jsx` and `.tsx` for router icons

---

src/icons/fileIcons.ts

Its a 3d model file, more info here [AC3D](https://www.inivis.com/)

Added AC3D (.ac) file icon.

---

icons/folder-event-open.svg
icons/folder-event.svg
src/icons/folderIcons.ts

Add folder event icon

---

.github/workflows/build.yml
src/icons/folderIcons.ts

A PR to make "databases" folders have the "database" icon !
Because if we make a folder containing databases, it usually means we have several of them, so the folder name should be plural 😄

Add "databases" to "database" folder names

---

src/icons/fileIcons.ts

Add .env icon for .env.testing used by AdonisJS.

Add .env.testing

---

src/icons/fileIcons.ts

Raster Image format
.afphoto (Affinity Photo)
.ase/.aseprite (Aseprite)
.clip (CLIP Paint Studio)
.cpt (Corel Photo Paint)
.heif/.heic (High Efficiency Image Format)
.kra (Krita)
.mdp (Medibang/FireAlpaca)
.pdn (Paint.NET)
.reb (Rebelle)
.sai (Paint Tool SAI)
.tga (Targa Graphic)
.xcf (GIMP)
3D file format
.blend (Blender)
.mesh (Mesh File)
.mqo (Metasequioa)
.pmd/.pmx/.vac/.vdp (MikuMikuDance)
.skp (SketchUp)
.vox (Voxel file)

Add various raster image and 3D format

---

src/icons/fileIcons.ts

Set json5 icon to json icon

---

src/icons/fileIcons.ts

qa env is very common in projects

Add tune icon to qa env file

---

src/icons/fileIcons.ts

Add the pug icon to the file names puglint supports: .pug-lintrc.json or .pug-lintrc.js or .pug-lintrc.json
https://github.com/pugjs/pug-lint#configuration-file

Add pug icon to pug lint files

---

src/icons/fileIcons.ts

Add support for .env.staging.local file

---

src/icons/fileIcons.ts

https://github.com/typicode/husky#upgrading-from-014
Husky also support `.huskyrc.js`

Add husky filename

---

src/icons/fileIcons.ts

Add filenames for semantic-release

---

src/icons/fileIcons.ts

haii, this links back to issue #712, adding the jest icons to the files `jest.config.mjs` and `jest.config.cjs`
let me know if anything else is needed :)
thanks,
edwin

add jest icons for jest.config.(m|c)js

---

src/icons/folderIcons.ts

Add folder icon for "sounds"

---

src/icons/fileIcons.ts

The `CHANGELOG` file is sometimes called `CHANGES`.

Alias CHANGELOG as CHANGES

---

src/icons/fileIcons.ts

Gulp [supports](https://github.com/gulpjs/gulp-cli/pull/214) configuration using `gulpfile.mjs`.

Alias gulpfile.js as gulpfile.mjs

---

src/icons/fileIcons.ts

https://preview.adonisjs.com/blog/introducing-adonisjs-v5/#good-bye-adonis-cli

Icon of AdonisJS's "ace" helper framework

---

src/icons/folderIcons.ts

Only to complete the pattern:
--- Missing "setting" and ".setting"
configuration -> configurations
config -> configs
? > settings
? > .settings
---

Add "setting" names to folder-config

---

.travis.yml
package-lock.json
package.json
src/helpers/fileConfig.ts
src/helpers/objects.ts
src/helpers/versioning.ts
src/icons/generator/fileGenerator.ts
src/icons/generator/folderGenerator.ts
src/icons/generator/iconOpacity.ts
src/icons/generator/iconSaturation.ts
src/icons/generator/jsonGenerator.ts
src/icons/generator/languageGenerator.ts
src/messages/outdated.ts
src/messages/update.ts
src/messages/welcome.ts
src/test/spec/icons/fileIcons.spec.ts
src/test/spec/icons/folderIcons.spec.ts
src/test/spec/icons/languageIcons.spec.ts
src/test/spec/index.ts
tsconfig.json

I did my best to document all changes in a separate commit. But it then grew out of proportion ending up doing 14 commits I would like to be able to fix that situation so you can accept the PR and I am not sure what to do from there.

Fix Typescript "hint" level warnings and trivial typing issue

---

src/icons/fileIcons.ts

For `meson_options.txt` reference: https://mesonbuild.com/Build-options.html#build-options.
And for WrapDB reference: https://mesonbuild.com/Wrap-dependency-system-manual.html.

Add meson_options.txt and meson wrapdb files

---

package-lock.json
package.json
src/extension.ts
src/helpers/versioning.ts

Fixes https://github.com/PKief/vscode-material-icon-theme/issues/896

Sync version key value

---

src/icons/folderIcons.ts

add plurial and singular of 'documents' and 'music'
- `folder-docs`: add 'document' folder name
- `folder-audio`: add 'musics' folder name

ADD: folder name for audio and docs

---

src/icons/fileIcons.ts

I think I just needed to add this change to enable the icon for the .nuxtignore file. If there is something else, I would accept some help to finish it. Thanks

Add nuxt icon to .nuxtignore file

---

src/icons/fileIcons.ts

we are on the final steps to have our own file extension.
i updated the `fileIcons.ts` file for that.

feat: add `.windi` file extension

---

src/icons/folderIcons.ts

feat: recognize `.venv/` as env folder by default

---

src/icons/folderIcons.ts

Link RestApi folder icon

---

src/icons/fileIcons.ts

Assign icon for `tsconfig.base.json`

---

src/icons/fileIcons.ts

Add some snowpack files

---

src/icons/folderIcons.ts

Fix typo: schemes -> schemas

---

src/icons/folderIcons.ts

Ref: https://github.com/wordpress/gutenberg
Ref: https://github.com/woocommerce/woocommerce-admin

Add support for storybook directory

---

src/icons/fileIcons.ts

Ref: https://github.com/johnbillion/query-monitor/tree/develop/tests

Add .env.dist file icon support

---

src/icons/fileIcons.ts

Add support for global git ignorance file

---

src/icons/fileIcons.ts

Add XML support for phpcs.xml.dist.sample

---

icons/folder-vercel-open.svg
icons/folder-vercel.svg
src/icons/fileIcons.ts
src/icons/folderIcons.ts

Add Vercel folder icon

---

.eslintignore
.vscode/launch.json
.vscode/tasks.json
.vscodeignore
build/web-extension.webpack.config.js
build/webpack.config.js
package-lock.json
package.json
src/commands/restoreConfig.ts
src/helpers/versioning.ts
src/messages/outdated.ts
src/messages/reload.ts
src/messages/start.ts
src/messages/update.ts
src/messages/welcome.ts
src/models/helpers/index.ts
src/models/helpers/themeStatus.ts
src/models/index.ts
src/web/extension.ts
tsconfig.json

Optimize extension for web usage

---

src/icons/fileIcons.ts

Add heex file extension

---

src/icons/fileIcons.ts

https://nextjs.org/docs/api-reference/next.config.js/introduction

Add `next.config.mjs` to next file icons

---

.github/workflows/color-check.yml
.github/workflows/greetings.yml
.github/workflows/release.yml
material-colors.yml
package.json

- Publish package to NPM registry
- Add greetings for issues and PRs of new contributors
- Add color check for SVG files in PRs
- Update meta information (funding, author name)

Improve build workflow

---

.github/workflows/color-check.yml

Ignore deleted SVG icons of a PR.

Update color check to ignore deleted SVG icons

---

README.md

Remove sponsor badge

---

icons/buildkite.svg
icons/folder-buildkite-open.svg
icons/folder-buildkite.svg
src/icons/folderIcons.ts

This PR introduces icons for the Buildkite folder.

feat: buildkite

---

src/icons/folderIcons.ts

```ts
{
name: 'folder-public',
folderNames: ['public', 'www', 'wwwroot', 'web', 'website', 'site'],
}
```
- update folder-public, add `site`
- At present, many websites in the project site take site as the name of the folder

feat: add site to folder-public

---

src/icons/folderIcons.ts

add jsx with react component icon

Components

---

src/helpers/changeDetection.ts

Fix: Workspace settings override user settings

---

package-lock.json
package.json

Fixes PKief/vscode-material-icon-theme#1556

Consider on-boarding to VS Code sponsor

---

src/icons/fileIcons.ts

feat: add `tsconfig.node.json`

---

src/icons/fileIcons.ts

This PR adds the `tauri.conf.json` file.
Closes: #1588

fix: add tauri.conf.json file

---

src/icons/fileIcons.ts

This PR adds the following file names to the `tsconfig `icon:
- `tsconfig.test.json`
- `tsconfig.e2e.json`

fix: tsconfig

---

src/icons/folderIcons.ts

This PR adds:
1.  the `__fixtures__` name to the `folder-test` icon.
2. the `fixture` and `fixtures` names to the `folder-mock` icon.

feat: fixtures folder

---

src/icons/fileIcons.ts

Add quasar.config.js (Closes #1599)

---

src/icons/fileIcons.ts

Compose icon

---

src/icons/fileIcons.ts

https://github.com/joedeandev/prettier-plugin-nginx#getting-started

feat: add `nginx` extensions

---

src/icons/folderIcons.ts

This PR adds 'bases' as a folderName for the folder-base Icon

add bases folderName

---

.github/workflows/release.yml

Hi,
Was not sure if this needed a created issue first, but spotted the typo and thought it's an easy thing to do :)

fix: typo in release yaml

---

src/icons/folderIcons.ts

Add 'fragments' as a folderName for the folder-components Icon

add Fragments folderName

---

src/icons/languageIcons.ts

Hello @PKief, it's me again. This PR fixes Dart language icon

feat: support Dart language

---

src/icons/fileIcons.ts

See https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new

Add eslint.config.js

---

src/icons/fileIcons.ts

for reference:
https://docs.fileformat.com/programming/jrxml/#:~:text=JRXML%20file%20example-,What%20is%20a%20JRXML%20file%3F,charts%2C%20parameters%2C%20and%20variables.

Add jrxml file extension to xml icon

---

src/icons/fileIcons.ts

Refs:
[SVGO - loadConfig](https://github.com/svg/svgo/blob/53ed57c7e1e84a4ced57ee972001aeb34d9015a4/lib/svgo-node.js#L37)

feat: enhance svgo icon support

---

src/icons/fileIcons.ts

Add `volar.config.js` to `vue-config` fileNames

Add support for Volar config file

---

src/icons/fileIcons.ts

Apology for the mistake, this should fix the CI for #1742.

Add missing `,` to `vue-config` fileNames

---

src/icons/folderIcons.ts

Add proto folder icon association

---

README.md

rm unlinked "official icons" list entry

---

src/icons/fileIcons.ts

Support [macOS icons](https://macosicons.com/)

feat: support icns file type

---

src/icons/folderIcons.ts

Add manager / moderator folder icon

---

src/icons/fileIcons.ts

Add icons for vscode files

---

src/icons/folderIcons.ts

Add Toolkit (Toolkits) and Toolbox (Toolboxes) folder icon associations

---

src/icons/folderIcons.ts

Added extra folder names to existing icons for a typical [Jekyll site folder structure](https://jekyllrb.com/docs/structure/)

Feature: Added icon support for typical jekyll folders

---

src/icons/fileIcons.ts

Add `code_of_conduct` to fileIcons.ts

---

src/icons/fileIcons.ts

Add  icon for .git-blame-ignore-revs

---

icons/bitbucket.svg

Update bitbucket icon

---

src/icons/fileIcons.ts

- https://github.com/sindresorhus/ink-link/blob/main/index.test-d.tsx
- https://github.com/sindresorhus/camelcase/blob/main/index.test-d.ts

Add type test file support

---

src/icons/fileIcons.ts

Add Serverless framework icon to all supported configuration files.

feat: Add support for all Serverless framework config extensions

---

src/icons/fileIcons.ts

I added all config filenames according to [https://stryker-mutator.io/docs/stryker-js/config-file/#usage](https://stryker-mutator.io/docs/stryker-js/config-file/#usage)

Add all possible stryker config filenames

---

icons/mermaid.svg
src/icons/fileIcons.ts

Add mermaid file icon

---

src/icons/folderIcons.ts

add public_html as an html folder icon

Update folderIcons.ts for HTML FolderIcon

---

README.md

Related to https://github.com/cssho/VSMarketplaceBadge/issues/18

Use shields.io for marketplace badges in README

---

src/icons/fileIcons.ts

Prettier released v3 and add [support config files in ESM](https://prettier.io/blog/2023/07/05/3.0.0.html#support-config-files-in-esm-13130httpsgithubcomprettierprettierpull13130-by-fiskerhttpsgithubcomfisker).

Prettier supports config files in ESM

---

icons/roblox.svg
src/icons/fileIcons.ts

Just decided it would be a nice idea to add Roblox Studio file icons. Especially useful for anyone using Visual Studio for their games using extensions like [Rojo](https://marketplace.visualstudio.com/items?itemName=evaera.vscode-rojo).

Adding Roblox Studio icons

---

src/icons/folderIcons.ts

[Icon Request] Secret Folder

---

README.md

Sponsor has stopped the collaboration.

Remove sponsors badge from readme

---

src/icons/fileIcons.ts

Added .o object extension and .zst compressed file extension to fileIcons.ts

Add .o and .zst extensions

---

icons/abap.svg
src/icons/fileIcons.ts

[Icon Request] ABAP

---

src/icons/fileIcons.ts

Fixes PKief/vscode-material-icon-theme#2012

[Icon Request] textlintrc with extension

---

src/icons/folderIcons.ts

feat: add the .config folder

---

src/icons/folderIcons.ts

feat: add tooling folder

---

src/icons/fileIcons.ts

[x] By creating this pull request, I acknowledge that I have read the [Contribution Guidelines](../../CONTRIBUTING.md) for this project.

Adjust azure pipelines filename

---

src/icons/fileIcons.ts

Add .stylelintrc.mjs

---

src/icons/fileIcons.ts

Support Bun's bunfig.toml file

---

src/icons/fileIcons.ts
src/icons/languageIcons.ts

Fix objective c and cpp associations as they were in conflicts with matlab language.
Closes #1243

Fix objective c and cpp associations

---

src/icons/folderIcons.ts

https://github.com/PKief/vscode-material-icon-theme/issues/2267

add backends folder icon

---

src/icons/fileIcons.ts

feat: slnx file extension (Closes #2275)

---

package.nls.ja.json

Added translation of changes added in #1916

feat(i18n): Add missing japanese translate

---

CODE_OF_CONDUCT.md

I have added a [**Code Of Conduct**](https://www.contributor-covenant.org/), which prescribes the rules of conduct for contributors, this is a contract that obligates **all** participants to treat each other **without** violence of **any** kind

Added `CODE_OF_CONDUCT.md`

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Change from `[ ]` to real checkbox ☑️

fix:  `pull_request_template.md`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/icon_request.md

I think it would be great to automatically add labels for issues to make it easier to navigate them

Added labels for issues

---

CONTRIBUTING.md
package.json
src/scripts/svg/checkSvgColors.ts

I fixed the color check which always LIED to me! 😠🔪
It didn't scan **any files at all**, because they weren't passed in `svg-color-linter` arguments

Fixed color checking

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

The contributor must first of all know the rules of conduct

A new item has been added to the checklist in the PR template

---

src/icons/folderIcons.ts

Added osx folder icon

---

src/core/icons/folderIcons.ts

Added `win32` folder icon

---

.github/workflows/icon-review.yml

In version `2.1.0` the image quality was improved, see https://github.com/PKief/svg-icon-review/pull/4

Updated `svg-icon-review` version (1.1.0 -> 2.1.0)

---

src/core/icons/fileIcons.ts

Add tape icon

---

.github/workflows/icon-review.yml

I improved the text in **Icon Review**, added a separate variable to store the number of icons, added words in the plural (for example, if someone added more than one icon, it will write "your icon**s**"), also improved the text with additional formatting

Improved text in icon-review

---

src/core/icons/folderIcons.ts

Added `ipynb` folder icon

---

src/core/icons/fileIcons.ts

See https://github.com/devcontainers/spec/blob/main/docs/specs/devcontainer-lockfile.md

Added `devcontainer-lock.json` file icon

---

.github/labeler.yml
.github/workflows/label.yml

Added labels for PR's that will help simplify navigation

Added labels for PR's

---

.github/labeler.yml
.github/workflows/label.yml

Reincorporates the Labeler action by @okineadev in #2487 and fixes (hopefully) the `labeler.yml` config.

ci: 🔄 fix failing labeler ci

---

src/core/icons/folderIcons.ts

Added the folder name 'distribution' to the folder-dist folder names.

Add 'distribution' to folder-dist

---

CONTRIBUTING.md
README.md

Fixes some broken links that were pointing to the old locations (from before the latest changes to the project structure).

docs: 📝 fix broken links in README and CONTRIBUTING guides

---

CONTRIBUTING.md

Closes #2502
Add Phorm AI badge to `CONTRIBUTING.md`.
* Add the Phorm AI badge code at the top of the `CONTRIBUTING.md` file.
* Ensure the badge code is in markdown format and correctly displays the badge.

Add Phorm AI badge

---

.github/workflows/build.yml
.github/workflows/icon-review.yml
.github/workflows/release.yml

...and fixed some emojis
Added artifact certification, with its help users can find out if this extension is really original
Read https://slsa.dev/

Added artifact attestation

---

.github/pull_request_template.md

Fixed PR template links

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/icon-request.yml

I added emojis to the issue template names to make them intuitive and easy to find

Added emojis in issue template names

---

src/core/icons/fileIcons.ts

Add Nest.js interceptor icon

---

src/core/icons/fileIcons.ts

Support icon for:
- `quasar.config.ts`
- `quasar.conf.ts`
- `quasar.config.cjs`

Add `ts`, `cjs` ext for `quasar`

---

icons/zeabur.svg
icons/zeabur_light.svg
src/core/icons/fileIcons.ts

Add `zeabur` file icon for [Zeabur](https://zeabur.com/) deploy config file.

Add `zeabur` file icon for `zeabur` deploy config file

---

icons/stackblitz.svg
src/core/icons/fileIcons.ts

Add stackblitz file icon

---

src/core/icons/fileIcons.ts

Add `.tazerc` and `.tazerc.json` filenames for `taze` icon

Add .tazerc and .tazerc.json filenames for taze icon

---

CONTRIBUTING.md

Deleted due to the fact that their service is practically not updated and it is not really needed

docs: :fire: Remove Phorm.ai badge

---

.github/copilot-instructions.md
.vscode/settings.json
CONTRIBUTING.md

Added instructions for **GitHub Copilot** to improve its interaction with this project
Its context now has `CONTRIBUTING.md` (so that it knows the rules for contributing to this project) and `src/architecture.md` so that it is familiar with the project architecture

feat: add Copilot instructions

---

src/core/icons/fileIcons.ts

feat: :sparkles: add icon for `.bun-version` file

---

.github/workflows/icon-review.yml

(maybe) Fixes failing "Icon review" workflow (https://github.com/material-extensions/vscode-material-icon-theme/actions/runs/11602388796/job/32312237325?pr=1560)

fix(workflows): :bug: try to fix failing `icon-review` workflow

---

.github/copilot-instructions.md

feat(docs): :memo: improve copilot instructions

---

src/core/icons/folderIcons.ts

feat: :sparkles: add new folder icons associations

---

.github/workflows/pr-title.yml

Install only `@commitlint/config-conventional` package globally instead of installing all packages

fix(workflows): :ambulance: fix failing `lint-pr-title` workflow

---

biome.jsonc

Updates the schema version in biome's config to match the package manager

chore: bump `biome.jsonc` schema version to `1.9.4`

---

src/core/icons/fileIcons.ts

Add another possible filename for sonarcloud.
See [github.com/SonarSource/sonar-scanner-msbuild/blob/master/docs/SonarQube.Analysis.xml](https://github.com/SonarSource/sonar-scanner-msbuild/blob/master/docs/SonarQube.Analysis.xml).

feat: add additional filename for sonarcloud

---

src/core/icons/fileIcons.ts

Add `tsconfig.client.json` file name to the tsconfig icon.

feat: add tsconfig.{client,declaration}.json icon associations

---

.vscode/extensions.json
.vscode/settings.json
CONTRIBUTING.md

- Update table of contents
- Use only markdown syntax for the headlines
- Add samples for the folder wildcards
- Add extension recommendations for editing markdown files
- Add settings for formatting markdown files with the markdown lint extension per default

docs: Update contributing file

---

biome.jsonc
package.json
renovate.json
src/core/generator/folderGenerator.ts
src/core/i18n/translations/lang-id.ts
src/core/icons/fileIcons.ts
src/core/icons/folderIcons.ts

Enforce similar linting of code with the build pipeline. Once a file is formatted in a different way from the project settings the build will fail. Different formattings make the maintenance of this project harder because PRs show more changes than necessary.

fix(workflows): ensure similar formatting with pipeline

---

src/core/icons/fileIcons.ts

Fixes #2712
Updated `fileicon.ts`:
```js
{
name: 'installation',
fileNames: [
'installation',
'installation.md',
'installation.rst',
'installation.txt',
'install',
'install.md',
'install.rst',
'install.txt',
],
},
```

feat: update `installation` file icon associations

---

src/core/icons/fileIcons.ts

feat: add `.do` file association for `tcl` icon

---

src/core/icons/fileIcons.ts

Added the following textlint configuration files:
- `.textlintrc.cjs`[^1]
- `.textlintignore`[^2]
[^1]: https://textlint.github.io/docs/getting-started.html#configuration
[^2]: https://textlint.github.io/docs/ignore.html

feat: enhance textlint configuration files

---

src/core/icons/fileIcons.ts

feat: ✨ use docker icon for `dockerfile.windows` file

---

src/core/icons/fileIcons.ts

Closes #2762
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/material-extensions/vscode-material-icon-theme/pull/2763?shareId=688e1c72-936c-4ac4-905e-ec9667d010a2).

feat: add icon for `compile_flags.txt` file

---

icons/ruff.svg
src/core/icons/fileIcons.ts

File Icon for ruff config file.
Closes: #2755

feat: ✨  icon for `ruff` config file

---

.vscodeignore

Having the license in the bundle is important. I've added it again.

fix: add license back to bundle

---

src/core/icons/folderIcons.ts

- add `pipeline` and `pipelines` to folder names
[x] By creating this pull request, I acknowledge that I have read the [Contribution Guidelines](../../CONTRIBUTING.md) for this project.

feat: add pipeline folder name

---

.github/workflows/potential-duplicates.yml

Adds a new workflow which can detect duplicates in the issues. Once a new issue is created this workflows checks if there's another issue with a similar title. If there's some issue available already the new issue will be marked with the label "potential-duplicate".

feat(workflows): :construction_worker: detect potential duplicates in issues

---

.github/workflows/color-check.yml
.github/workflows/icon-review.yml
.github/workflows/potential-duplicates.yml
.github/workflows/pr-title.yml

Also fixes invalid "Potentional duplicates" workflow

ci: ♻️ Use a limited range of files for checkout

---

.devcontainer/devcontainer.json

* Added `huntertran.auto-markdown-toc` extension

chore(devcontainer): ⏫ update preinstalled extensions list

---

CONTRIBUTING.md
README.md

There are all the icons we need - https://fonts.google.com/icons

docs: 📝 use only one recommended icon source

---

.github/workflows/release.yml

refactor(ci): ♻️ use `HUSKY: 0` in env according to the DRY

---

.github/workflows/pr-closed.yml
.github/workflows/pr-title.yml

refactor(ci): ♻️ use reusable workflows

---

.github/workflows/pr-closed.yml

fix: fix pr-closed.yml

---

src/core/icons/fileIcons.ts

- Added the `typst.toml`, the manifest file for the Typst package[^1]
[^1]: https://github.com/typst/packages

feat: add Typst manifest file

---

src/core/icons/folderIcons.ts

feat: add `kits` folder name for `tools` folder icon

---

src/core/icons/fileIcons.ts

feat: add wrangler icon for wrangler.json and wrangler.jsonc

---

src/core/icons/fileIcons.ts
src/core/icons/folderIcons.ts

Added _OpenOffice Base_ database files `.odb` to the database file extensions.

Update database file extensions

---

src/core/icons/fileIcons.ts

We recently added a [new config file](https://github.com/go-task/task/pull/1982) to Task. This PR associates the config file with the existing Taskfile logo.

feat: .taskrc.yml files

---

src/core/icons/folderIcons.ts

add `const` and `consts` to constant folder icon

feat: add const and consts to constant folder icon

---

src/core/icons/fileIcons.ts

Supplement to #1934.
Add `.qa-mincloudrc` icon.

feat: add .qa-mincloudrc icon

---

src/core/icons/fileIcons.ts

- Add new fileName to the copilot file icon

feat: update copilot icon filenames

---

src/core/icons/fileIcons.ts

close #3155 
Added missing target files.

feat(icons): Add files compatible with eslint

---

icons/console.svg

This pull request proposes a redesign of the [`console` icon](https://github.com/material-extensions/vscode-material-icon-theme/blob/de6b8c5384d287ff9a9af9cf6af1032a4508dd36/icons/console.svg) so that its lines are aligned to the 16 px grid.
The concept, color, and proportions have been preserved to avoid changing the user’s perception. The borders are 1 px thick, except for the top one, which is 3 px. The internal shapes are 1.5 px — in my opinion, 1 px would be too thin and 2 px too thick, so I went with a middle ground.
---
_If anyone has suggestions or feedback, feel free to share!_

refactor: update `console` icon for a pixel-perfect alignment
